### ISSUE TITLE
PRACTICA CONEXION

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-topicos_a-4bs-idm#1]
Integrantes:
Diergo Cruz Cruz
Irvin Jiménez Sánchez
Marco Uriel Rosas García
[Uploading PRACTICA DE CONEXION_Topicos Avanzados de Programacion.pdf…]()

**Comment by josealfredo79** [comment]
Bien hecho y revisado...calificacion 20
